---
apiVersion: v1
kind: Service
metadata:
  name: svc-db
  namespace: jenkins
  labels:
    app: database-service
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: database-service
  type: ClusterIP
