---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: jenkins
  labels:
    app: service-rest
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: service-rest
  type: NodePort
